import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This matches the 'procs' id logic
  updatesSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates sidebar from the /procs folder
    },
  ],
};

export default sidebars;